### ISSUE TITLE
map content json file is poorly optimized

### ISSUE THREAD

**Issue by Yokkako** [InventiveRhythm/fluXis#51]
Basically the issue is that there are a lot of unnecessary repeating parts in the json file (such as "IsLongNote"), which heavily inflates the file size of all maps

Personally, I have over 50k maps in Quaver/osu, so I could definitely see this being an issue for some players

I guess it would be best to just rethink the whole concept of how maps are stored, because the way it currently is, filesize is nearly tripled compared to other games (example Quaver)

Check attached screenshots, same map in fluxis and in Quaver format

![fluxis](https://github.com/TeamFluXis/fluXis/assets/76214999/460b8fa4-27b6-4053-a10c-bbcc263e1402)

![quaver](https://github.com/TeamFluXis/fluXis/assets/76214999/3641f9e8-4136-4ed1-a490-8094707b8a38)

**Comment by flustix** [comment]
Okay so I went thru the code and found the issue.

The file size is only that big because I messed up and Quaver conversions contain the same map twice and I did not add the `JsonIgnore` atrribute.

![image](https://github.com/TeamFluXis/fluXis/assets/65369281/59aab9b5-fabf-4d5d-abe3-67e84e12e587)

*The extra `QuaverMap` inside the `MapInfo` is used for auto-imported maps.*

**Comment by flustix** [comment]
Adding said attribute halved the file sizes.

Before
![image](https://github.com/TeamFluXis/fluXis/assets/65369281/28c02e00-bdac-418a-9dfd-df356f07c2e4)

After
![image](https://github.com/TeamFluXis/fluXis/assets/65369281/11253dce-da4f-443f-a7d3-f363e69d1510)
